# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85a1ad94ecd059fec81d145f567c79cad2a1b6413cad3bb50f407d485e4d9b030d18d0c656e62eb3b9668d4ca14342db8cd6678561ecb95ac14c9a5638d1215c

test:
  secret_key_base: 1f5bade4efd1ee35d891435d46007f24ffae1711b1401b12c949e42fee4b91519b9f45765d5b4b4754e46b45384704e96e410e14056211ebe736ecf4a35abfaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
